name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        eslint: [7, 8]
        node-version: [14.x, 16.x, 17.x, 18.x, 19.x, 20.x]

    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v2

      - name: ✨ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 📥 Install ESLint v${{ matrix.eslint }}
        run: npm install eslint@${{ matrix.eslint }}

      - name: 🔬 Run test script
        run: npm run test
